case $- in
  *i*) ;;
    *) return;;
esac

export OSH='/usr/local/share/oh-my-bash'
OSH_THEME="font"
HIST_STAMPS='yyyy-mm-dd'

OMB_USE_SUDO=true

completions=(
  git
  composer
  ssh
)

aliases=(
  general
)

plugins=(
  git
  bashmarks
)

source "$OSH"/oh-my-bash.sh

. "$HOME/.cargo/env"
eval "$(zoxide init bash)"
